config/routes.rb
Rails.application.routes.draw do
  resources :customers

  get 'news/index'

  get 'about/index'

  get 'contact/index'

  get 'welcome/index'
  root 'welcome#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :addr_num, :addr_name)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active{
	background-color: #4CAF50;
}
</style>
<ul>
  <li><a href="http://localhost:3000">Home</a></li>
  <li><a href="http://localhost:3000/news/index">News</a></li>
  <li><a href="http://localhost:3000/contact/index">Contact</a></li>
  <li><a href="http://localhost:3000/about/index">About</a></li>
</ul>
<style>
input[type=submit]
{
	color: white;
	background-color: #4CAF50;
	margin: 4px 2px;
	padding: 16px 32px;
	border: solid;
	text-decoration: none;
	cursor: pointer;
	font-size: 15px;
	position: absolute;
	right:    0;
	bottom:   0;

}
input[type=button]
{
	color: white;
	background-color: #4CAF50;
	margin: 4px 2px;
	padding: 16px 32px;
	border: solid;
	text-decoration: none;
	cursor: pointer;
	font-size: 15px;
	position: absolute;
	left:0;
	bottom: 0;

}
body {
	background-color:black;
	 }
h1	 {
	color:red;
	font-size: 350%;
	text-align: center;

	 }
p    {
	color:blue;
	text-align:center;
	font-size: 200%;
	 }

p.about-site
{
	color:yellow;
	text-align:center;
	font-size: 100%;
}
</style>
</head>
<body background="/pizzabckg.jpg">
<body>
<h1>About Uncle Joe's!</h1>
<p>This is the about page!</p>
<p class=about-site>Here is some text about our Uncle Pizza King.</p>
<img src="/pizzaking.gif" alt="Pizza King" style="width:200px;height:200px;" align="top">
</body>
</html>

app/views/contact/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active{
	background-color: #4CAF50;
}
</style>
<ul>
  <li><a href="/Users/OrlandoGarcia/Desktop/Pizza King/homepizzaking.html">Home</a></li>
  <li><a href="/Users/OrlandoGarcia/Desktop/Pizza King/newspizzaking.html">News</a></li>
  <li><a href="/Users/OrlandoGarcia/Desktop/Pizza King/contactpizzaking.html">Contact</a></li>
  <li><a href="/Users/OrlandoGarcia/Desktop/Pizza King/aboutpizzaking.html">About</a></li>
</ul>
<style>
input[type=submit]
{
	color: white;
	background-color: #4CAF50;
	margin: 4px 2px;
	padding: 16px 32px;
	border: solid;
	text-decoration: none;
	cursor: pointer;
	font-size: 15px;
	position: absolute;
	right:    0;
	bottom:   0;

}
input[type=button]
{
	color: white;
	background-color: #4CAF50;
	margin: 4px 2px;
	padding: 16px 32px;
	border: solid;
	text-decoration: none;
	cursor: pointer;
	font-size: 15px;
	position: absolute;
	left:0;
	bottom: 0;

}
body {
	background-color:black;
	 }
h1	 {
	color:red;
	font-size: 350%;
	text-align: center;

	 }
p    {
	color:blue;
	text-align:center;
	font-size: 200%;
	 }
p.contact-site
{
	color:yellow;
	text-align:center;
	font-size: 100%;
}
</style>
</head>
<body background="pizzabckg.jpg">
<body>
<h1>Contact Uncle Joe's!</h1>
<p>This is the contact page!</p>
<p class=contact-site>This is some contact info!!</p>
<img src="pizzaking.gif" alt="Pizza King" style="width:200px;height:200px;" align="top">
</body>
</html>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :addr_num %><br>
    <%= f.text_field :addr_num %>
  </div>
  <div class="field">
    <%= f.label :addr_name %><br>
    <%= f.text_field :addr_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Addr num</th>
      <th>Addr name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.addr_num %></td>
        <td><%= customer.addr_name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Addr num:</strong>
  <%= @customer.addr_num %>
</p>

<p>
  <strong>Addr name:</strong>
  <%= @customer.addr_name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VanillaIce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active{
	background-color: #4CAF50;
}
</style>
<ul>
  <li><a href="http://localhost:3000">Home</a></li>
  <li><a href="http://localhost:3000/news/index">News</a></li>
  <li><a href="http://localhost:3000/contact/index">Contact</a></li>
  <li><a href="http://localhost:3000/about/index">About</a></li>
</ul>
<style>
input[type=submit]
{
	color: white;
	background-color: #4CAF50;
	margin: 4px 2px;
	padding: 16px 32px;
	border: solid;
	text-decoration: none;
	cursor: pointer;
	font-size: 15px;
	position: absolute;
	right:    0;
	bottom:   0;

}
input[type=button]
{
	color: white;
	background-color: #4CAF50;
	margin: 4px 2px;
	padding: 16px 32px;
	border: solid;
	text-decoration: none;
	cursor: pointer;
	font-size: 15px;
	position: absolute;
	left:0;
	bottom: 0;

}
body {
	background-color:black;
	 }
h1	 {
	color:red;
	font-size: 350%;
	text-align: center;

	 }
p    {
	color:blue;
	text-align:center;
	font-size: 200%;
	 }
p.news-site
{
	color:yellow;
	text-align:center;
	font-size: 100%;
}
</style>
</head>
<body background="/pizzabckg.jpg">
<body>
<h1>News about Uncle Joe's!</h1>
<p>This is the news page!</p>
<p class=news-site>This is some news about Pizza King!</p>
<img src="/pizzaking.gif" alt="Pizza King" style="width:200px;height:200px;" align="top">
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
    position: fixed;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active{
	background-color: #4CAF50;
}
</style>
<ul>
  <li><a href="http://localhost:3000">Home</a></li>
  <li><a href="http://localhost:3000/news/index">News</a></li>
  <li><a href="http://localhost:3000/contact/index">Contact</a></li>
  <li><a href="http://localhost:3000/about/index">About</a></li>
</ul>
<style>
input[type=submit]
{
	color: white;
	background-color: #4CAF50;
	margin: 4px 2px;
	padding: 16px 32px;
	border: solid;
	text-decoration: none;
	cursor: pointer;
	font-size: 15px;
	position: fixed;
	right:    0;
	bottom:   0;

}

input[type=submit1]
{
	color: white;
	background-color: #4CAF50;
	margin: 4px 2px;
	padding: 16px 32px;
	border: solid;
	text-decoration: none;
	cursor: pointer;
	font-size: 15px;
	position: fixed;
	bottom:   0;

}
body {
	background-color:black;
	 }
h1	 {
	color:red;
	font-size: 350%;
	text-align: center;

	 }
p    {
	color:blue;
	text-align:center;
	font-size: 200%;
	 }
</style>
</head>

<body background="/pizzabckg.jpg">
<body>
<h1>Uncle Joe's Pizza King</h1>
<p>Welcome to Uncle Joe's Pizza!</p>
<img src="/pizzaking.gif" alt="Pizza King" style="width:200px;height:200px;" align="top">
</body>


<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

</style>
</head>
<body>
<table  style="width:35%">
  <tr>
    <th style="width:20%" bgcolor="FF0000">Restaurant</th>
    <th style="width:20%" bgcolor="FF0000">Best Pie Sold</th>
    <th style="width:20%" bgcolor="FF0000">Best 5 All-Time Selling Pies!</th>
 </tr>
  <tr>,
    <td bgcolor="#ffffff">Bad Juju's Pizza</font></td>
    <td bgcolor="ffff00">Bad</td>
    <td bgcolor="#ffffff">1.No Name pizza @ Harry Garry's - 112,901</td>
  </tr>
  <tr>
    <td bgcolor="#ffffff">Harry Garry's Pizza Pie</td>
    <td bgcolor="ffff00">Harry's</td>
    <td bgcolor="#ffffff">2.Steak and Cheese @ Mike's Pies - 74,894</td>
  </tr>
  <tr>
    <td bgcolor="#ffffff">Hoang's Pizzeria</td>
    <td bgcolor="ffff00">Fish</td>
    <td bgcolor="#ffffff">3.Bad @ Juju's - 37,751</td>
  </tr>
  <tr>
    <td bgcolor="#ffffff">Little Roman's</td>
    <td bgcolor="ffff00">Pepperoni</td>
    <td bgcolor="#ffffff">4.Pepperoni @ Little Roman's - 37,746</td>
  </tr>
  <tr>
    <td bgcolor="#ffffff">Mike's Pies</td>
    <td bgcolor="ffff00">Steak and Cheese</td>
    <td bgcolor="#ffffff">5. Fish @ Hoang's - 37,321</td>
  </tr>
  <tr>
    <td bgcolor="#ffffff">Poker Cards</td>
    <td bgcolor="ffff00">Meatser</td>
  </tr>
  <tr>
    <td bgcolor="#ffffff">The Cicilian's</td>
    <td bgcolor="ffff00">Funky Medina</td>
  </tr>
   <tr>
    <td bgcolor="#ffffff">Tiny Pizza's</td>
    <td bgcolor="ffff00">Sweet</td>
  </tr>
</table>
<br />
<br />
<body text="silver">
	<form action="demo_form.asp">
	 Name: <input type="text" size="60"> <br />
	 Address_Num: <input type="text" size="60"><br>
	 Address_Name: <input type="text" size="60"><br>
	 <input type="submit" value="Order Pizza">
	 </form>
</body>
</html>